### ISSUE TITLE
Could I use this system to update a "date due" custom field

### ISSUE THREAD

**Issue by psyciknz** [B-urb/doclytics#107]
I'm trying to figure out if there is some way in paperless (short of doing it manually), if I can add to documents with some payment due type keywords, the date that the bill is due.

I already manually tag something as "unpaid" if I need to pay it, and then if there's a future date, has started adding that date as a custom field.  This is then sent via pushover as a reminder until I set to it to "paid".

Was just curious if some sort of AI system could automate parts of this (kinda struggling to see how ai can be used).

**Comment by B-urb** [comment]
Yes, this should work in general. I would't depend any critical notifications on it, because the llm can be flaky sometime, but in theory, you can just add the payment_due custom field and adjust the prompt. Only problem is, that at the moment it is formatted as text and not date, but i am working on that
